# Generated by Django 4.1.7 on 2023-03-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(choices=[('OM', 'Ordinary Worker'), ('DP', 'Department Head'), ('MN', 'Manager'), ('DI', 'Director'), ('BG', 'Big Boss')], max_length=2)),
                ('salary', models.IntegerField()),
                ('recruitment', models.DateField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boss', to='employees.employees', verbose_name='Руководитель')),
            ],
        ),
    ]
