# Generated by Django 4.1.7 on 2023-02-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sur_name', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.IntegerField(choices=[('5', 'number_5'), ('4', 'number_4'), ('3', 'number_3'), ('2', 'number_2'), ('1', 'number_1')], default='5')),
                ('salary', models.IntegerField()),
                ('recruitment', models.DateField(auto_now_add=True)),
                ('subordinates', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='employees.employees')),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='boss', to='employees.employees')),
            ],
        ),
    ]
